---
abstract: 'find year, month, day from (filename) strings'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Data::Dumper: '0'
  Date::Extract: '0'
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Date-Find
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '5'
  File::Basename: '0'
  File::Copy: '0'
  File::Path: '0'
  File::Spec: '0'
  Getopt::Long: '0'
  experimental: '0.036'
  perl: '5.020'
resources:
  bugtracker: https://github.com/Corion/Date-Find/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/Date-Find.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
